### PR TITLE
ContainerAwareMigrationService

### PR DESCRIPTION
**Pull request by HadesArchitect**
Hi. 

It's not a real merge request yet, I only want to assure that this functionality is required in the project. In case of your interest I can add tests + docs + whatever.

Description: In some cases people may need an access to a symfony container during a migration. For this purpose we can mark a migration as a container-aware, and the service will inject Container into the migration.

[Original Idea](https://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#container-aware-migrations)

Todo: 
- Real implementation
- Configurable class for symfony service
- Tests
- Docs 

To implement ContainerAware functionality in a migration I offer to use [ContainerAwareTrait](https://github.com/symfony/dependency-injection/blob/master/ContainerAwareTrait.php).

### CODE REVIEW

**Comment by amyboyd** [comment]
Hi Alex,

Thanks for the pull request.

Getting the service container does sound like a useful feature. I'd be happy for this to be added. Some things to think about for the final implementation:
- The `mongrate` library doesn't depend on `symfony/dependency-injection`, so setting the service container would have to be done in `mongrate-bundle`. (You have already done this so :+1: )
- `ContainerAwareTrait` could be added to a migration class **if the migration is tied to MongrateBundle** and **not** if not the migration class is stand-alone.
- There is a [trait](https://github.com/mongrate/mongrate/blob/master/src/Mongrate/Migration/Migration.php) that migration classes [use](https://github.com/mongrate/mongrate/blob/master/resources/migration-template/Migration.php#L14) to allow dependencies to be added. If PSR-11 ever gets completed and Symfony implements PSR-11, then we could put a `setContainer()` method into this trait. But not now.

If you can get a working solution in `mongrate-bundle` and add a test, that would be great.

Thanks!

**Comment by HadesArchitect** [comment]
For sure, I will add it soon. Thanks.

**Comment by HadesArchitect** [comment]
Status update: it looks like it's done.
Documentation: https://github.com/mongrate/mongrate.com/pull/3

Tests should be ok in few minutes.

**Comment by HadesArchitect** [comment]
Ok, there are the failing builds: https://travis-ci.org/mongrate/mongrate-bundle/builds/140551891

The reason is, the lowest allowed symfony version doesn't have recommended ContainerAwareTrait.

Compare:
- https://travis-ci.org/mongrate/mongrate-bundle/jobs/140551895#L259
- https://travis-ci.org/mongrate/mongrate-bundle/jobs/140551893#L216

Possible solution:
- update minimum dependency version to ~2.4 OR
- remove trait and implement ContainerAwareInterface manually.

This trait was introduced in https://github.com/symfony/dependency-injection/commit/29c6f50fcb4a4b1261a18dc1894ed206ad128582#diff-0b6248e9ec672d3f043b6bb0787dc194 approximately 3 years ago. 

ping @amyboyd

**Comment by HadesArchitect** [comment]
Well, from one point of view, Symfony:2.3 is already out of maintenance, but still one year before EOL, so we have to support it.

From another point of view, mongrate/mongrate already [has trait](https://github.com/mongrate/mongrate/blob/master/src/Mongrate/Migration/Migration.php#L10), though it's optional.

Perhaps it makes sense to release a new bundle version with more strict requirements?

**Comment by amyboyd** [comment]
I've used Packagist's API to chart how many downloads each version of Symfony had in the last month:

image

Based on this, I think it's acceptable to drop support for Symfony 2.3.

Going to merge this soon.

**Comment by amyboyd** [comment]
Manually merged via 2d56b7f

Thank you!

**Comment by amyboyd** [comment]
If needed again, the data behind the graph above is available at: https://github.com/amyboyd/php-package-versions/blob/master/symfony-symfony.csv

**Comment by HadesArchitect** [comment]
Ok, thanks!

**Pull request closed without merging**
